name: Docker Image CI

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/bake-action@v4
        with:
          pull: true
          push: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.tags=rdurica/onboardly:${{ github.ref_name }}
            *.tags=rdurica/onboardly:latest
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{ github.ref }},mode=max

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image Confirmation
        run: echo "Docker image successfully built and pushed."
